aservo/confapi-confluence-plugin

pom.xml, src/main/java/de/aservo/atlassian/confluence/confapi/rest/MailServerResource.java, src/main/java/de/aservo/atlassian/confluence/confapi/rest/SettingsResource.java
Wurde vergessen. Deswegen würde ich die REST Endpoints gerne mit selbstgeschriebenen Asserts unittesten.
=> Use AdminOnlyResourceFilter in resources that used access helper before

index.adoc, pom.xml, src/main/java/de/aservo/atlassian/confluence/confapi/rest/LicenceResource.java, src/test/java/de/aservo/atlassian/confluence/confapi/rest/LicenseResourceTest.java
license resource implementation
The license resource can be used to read or set the current Confluence
product license.
=> license resource

index.adoc, src/main/java/de/aservo/atlassian/confluence/confapi/model/PermissionAnonymousAccessBean.java, src/main/java/de/aservo/atlassian/confluence/confapi/rest/PermissionsResource.java, src/test/java/de/aservo/atlassian/confluence/confapi/rest/PermissionsResourceTest.java
This resource is used to configure global anonymous access in Confluence.
=> anonymous access implementation

src/main/java/de/aservo/atlassian/confluence/confapi/rest/DirectoriesResourceImpl.java, src/main/java/de/aservo/atlassian/confluence/confapi/rest/LicencesResourceImpl.java, src/main/java/de/aservo/atlassian/confluence/confapi/rest/MailServerResourceImpl.java, src/main/java/de/aservo/atlassian/confluence/confapi/rest/PingResourceImpl.java, src/main/java/de/aservo/atlassian/confluence/confapi/rest/SettingsResourceImpl.java, src/test/java/de/aservo/atlassian/confluence/confapi/rest/DirectoriesResourceTest.java, src/test/java/de/aservo/atlassian/confluence/confapi/rest/LicensesResourceTest.java, src/test/java/de/aservo/atlassian/confluence/confapi/rest/MailServerResourceTest.java, src/test/java/de/aservo/atlassian/confluence/confapi/rest/PingResourceTest.java, src/test/java/de/aservo/atlassian/confluence/confapi/rest/SettingsResourceTest.java
Sollte den Build fixen nach dem Merge von https://github.com/aservo/confapi-commons/pull/15
Kannst ja den Branch noch einmal bei dir lokal testen.
=> Fix build after using resource interfaces, remove obsolete tests

index.adoc, src/main/java/de/aservo/atlassian/confluence/confapi/rest/ApplicationLinksResourceImpl.java
Thios commit adds the application links resource impl endpoint.
=> Application Links Resource Endpoint

src/main/java/de/aservo/atlassian/confluence/confapi/rest/MailServerResourceImpl.java, src/main/java/de/aservo/atlassian/confluence/confapi/service/MailServerServiceImpl.java, src/test/java/de/aservo/atlassian/confluence/confapi/service/MailServerServiceTest.java
Based on the new commons resource abstraction this commit contains the
mailserver interface for confluence as well as adapted unit tests.
=> Mailserver Resource Interface Implementation

src/main/java/de/aservo/atlassian/confluence/confapi/rest/SettingsResourceImpl.java, src/main/java/de/aservo/atlassian/confluence/confapi/service/SettingsServiceImpl.java, src/test/java/de/aservo/atlassian/confluence/confapi/service/SettingsServiceTest.java
Based on the new commons resource abstraction this commit contains the
settings interface for confluence as well as adapted unit tests.
=> Settings Resource Interface Implementation

index.adoc, src/main/java/de/aservo/atlassian/confluence/confapi/rest/GadgetsResourceImpl.java, src/main/java/de/aservo/atlassian/confluence/confapi/service/GadgetsServiceImpl.java, src/test/java/de/aservo/atlassian/confluence/confapi/service/GadgetsServiceTest.java
Based on the new commons resource abstraction this commit contains the
gadgets interface for confluence as well as adapted unit tests.
=> Gadgets Resource Interface Implementation

pom.xml, src/test/java/it/de/aservo/atlassian/confluence/confapi/rest/MailServerPopResourceTest.java, src/test/java/it/de/aservo/atlassian/confluence/confapi/rest/MailServerSmtpResourceTest.java, src/test/java/it/de/aservo/atlassian/confluence/confapi/rest/UserResourceTest.java
This commit adds integration tests based on the abstract test implementations
provided in the commons lib.
=> Mailserver and Users integration tests implementation

pom.xml
Ich habe hier auch ein bisschen nach Dependency Management / Nicht Dependency Management umsortiert.
=> Use dependency management from ConfAPI commons

index.adoc, pom.xml
Beim letzten PR leider ein Vorkommen des alten Package Strings übersehen, deswegen ist die Doku rausgeflogen...
=> Fix Swagger documentation generation

index.adoc, pom.xml, src/main/java/de/aservo/confapi/confluence/model/BackupBean.java, src/main/java/de/aservo/confapi/confluence/model/BackupQueueBean.java, src/main/java/de/aservo/confapi/confluence/rest/BackupResourceImpl.java, src/main/java/de/aservo/confapi/confluence/rest/api/BackupResource.java, src/main/java/de/aservo/confapi/confluence/service/BackupServiceImpl.java, src/main/java/de/aservo/confapi/confluence/service/api/BackupService.java, src/main/java/de/aservo/confapi/confluence/util/HttpUtil.java, src/test/java/de/aservo/confapi/confluence/model/BackupBeanTest.java, src/test/java/de/aservo/confapi/confluence/rest/BackupResourceTest.java, src/test/java/de/aservo/confapi/confluence/service/BackupServiceTest.java, src/test/java/de/aservo/confapi/confluence/util/HttpUtilTest.java, src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
Other than originally planned, I now splitted up the endpoints for export and import into separate PR's in order to make it easier to implement and to review.
=> REST endpoint for export of spaces

index.adoc, pom.xml, src/main/java/de/aservo/confapi/confluence/model/util/ApplicationLinkBeanUtil.java, src/main/java/de/aservo/confapi/confluence/service/ApplicationLinkServiceImpl.java, src/main/java/de/aservo/confapi/confluence/service/DirectoryServiceImpl.java, src/main/java/de/aservo/confapi/confluence/service/GadgetsServiceImpl.java, src/main/java/de/aservo/confapi/confluence/service/LicensesServiceImpl.java, src/test/java/com/atlassian/confluence/settings/setup/DefaultApplicationLink.java, src/test/java/de/aservo/confapi/confluence/service/ApplicationLinkServiceTest.java, src/test/java/de/aservo/confapi/confluence/util/FilePartUtilTest.java
This commit implementes confapi-commons 0.24 interface implementation stubs
and the actual implementation for application links.
=> Extended GET / PUT / DELETE resources

src/main/java/de/aservo/confapi/confluence/service/ApplicationLinkServiceImpl.java
This commit fixes an issue with updating applinks from request beans.
Now, all link ids for update are retrieved from the system (not from
the request bean). Non existing links are added from scratch.
=> Fix PUT application links

index.adoc, src/main/java/de/aservo/confapi/confluence/service/GadgetsServiceImpl.java, src/test/java/de/aservo/confapi/confluence/service/GadgetsServiceTest.java
This commit implements confapi-commons 0.24 interface implementation
for the gadgets resource.
=> Extended GET / PUT / DELETE resources (gadgets)

index.adoc, src/main/java/de/aservo/confapi/confluence/model/util/DirectoryBeanUtil.java, src/main/java/de/aservo/confapi/confluence/service/DirectoryServiceImpl.java, src/test/java/de/aservo/confapi/confluence/service/DirectoryServiceTest.java
This commit implementes confapi-commons 0.24 interface implementation
for the directories resource.
=> Extended GET / PUT / DELETE resources (directories)

index.adoc, pom.xml, src/main/java/de/aservo/confapi/confluence/model/util/SettingsBrandingColorSchemeBeanUtil.java, src/main/java/de/aservo/confapi/confluence/rest/SettingsBrandingResourceImpl.java, src/main/java/de/aservo/confapi/confluence/service/SettingsBrandingServiceImpl.java, src/test/java/de/aservo/confapi/confluence/model/util/SettingsColourSchemeBeanUtilTest.java, src/test/java/de/aservo/confapi/confluence/service/SettingsBrandingServiceTest.java
This commit implements the branding API resource defined in
confapi-commons 0.30 for Confluence.
=> Branding API implementation

.gitignore, index.adoc, pom.xml, src/main/java/de/aservo/confapi/confluence/service/SettingsServiceImpl.java, src/test/java/de/aservo/confapi/confluence/service/SettingsServiceTest.java
Add confluence contact message.
=> Add contact message.

index.adoc, src/main/java/de/aservo/confapi/confluence/service/SettingsServiceImpl.java, src/test/java/com/atlassian/confluence/settings/setup/DefaultTestSettings.java, src/test/java/com/atlassian/confluence/settings/setup/OtherTestSettings.java, src/test/java/de/aservo/confapi/confluence/service/SettingsServiceTest.java
Add the ability to set external user management.
=> Add externalUserManagement settings.

index.adoc, src/main/java/de/aservo/confapi/confluence/service/UsersServiceImpl.java, src/test/java/de/aservo/confapi/confluence/service/UserServiceTest.java
Confluence now supports changing usernames.
=> Adding functionality to change username.

index.adoc, pom.xml, src/main/java/de/aservo/confapi/confluence/rest/PingResourceImpl.java, src/main/resources/openapi.yaml, src/test/java/de/aservo/confapi/confluence/filter/SysAdminOnlyResourceFilterTest.java, src/test/java/de/aservo/confapi/confluence/model/type/DefaultAuthenticationScenarioTest.java, src/test/java/de/aservo/confapi/confluence/model/util/ApplicationLinkBeanUtilTest.java, src/test/java/de/aservo/confapi/confluence/model/util/DirectoryBeanUtilTest.java, src/test/java/de/aservo/confapi/confluence/model/util/LicenseBeanUtilTest.java, src/test/java/de/aservo/confapi/confluence/model/util/MailServerPopBeanUtilTest.java, src/test/java/de/aservo/confapi/confluence/model/util/MailServerSmtpBeanUtilTest.java, src/test/java/de/aservo/confapi/confluence/model/util/SettingsColourSchemeBeanUtilTest.java, src/test/java/de/aservo/confapi/confluence/model/util/UserBeanUtilTest.java, src/test/java/de/aservo/confapi/confluence/rest/PermissionsResourceTest.java, src/test/java/de/aservo/confapi/confluence/service/ApplicationLinkServiceTest.java, src/test/java/de/aservo/confapi/confluence/service/CachesServiceTest.java, src/test/java/de/aservo/confapi/confluence/service/DirectoryServiceTest.java, src/test/java/de/aservo/confapi/confluence/service/GadgetsServiceTest.java, src/test/java/de/aservo/confapi/confluence/service/LicensesServiceTest.java, src/test/java/de/aservo/confapi/confluence/service/MailServerServiceTest.java, src/test/java/de/aservo/confapi/confluence/service/PermissionsServiceTest.java, src/test/java/de/aservo/confapi/confluence/service/SettingsBrandingServiceTest.java, src/test/java/de/aservo/confapi/confluence/service/SettingsServiceTest.java, src/test/java/de/aservo/confapi/confluence/service/UserServiceTest.java, src/test/java/it/de/aservo/confapi/confluence/rest/PermissionsResourceFuncTest.java
Also regenerate documentation.
=> Upgrade Confluence and other versions, fix running JUnit 5 tests

src/main/java/de/aservo/confapi/confluence/service/SettingsServiceImpl.java, src/test/java/de/aservo/confapi/confluence/service/SettingsServiceTest.java
This replaces the old deprecated manager with the new more specific one.
=> Change over SettingsManager to GlobalGettingsManager

index.adoc, pom.xml, src/main/java/de/aservo/confapi/confluence/model/util/AuthenticationIdpBeanUtil.java, src/main/java/de/aservo/confapi/confluence/model/util/AuthenticationSsoBeanUtil.java, src/main/java/de/aservo/confapi/confluence/rest/AuthenticationResourceImpl.java, src/main/java/de/aservo/confapi/confluence/service/AuthenticationServiceImpl.java, src/test/java/de/aservo/confapi/confluence/model/util/AuthenticationIdpBeanUtilTest.java, src/test/java/de/aservo/confapi/confluence/service/AuthenticationServiceTest.java
Closes https://github.com/aservo/confapi-confluence-plugin/issues/74
=> Allow setting authentication IDP and SSO config
